terraform {
  required_version = "~> 1.13"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "4.53"
    }
    azapi = {
      source  = "Azure/azapi"
      version = "2.7"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
    random = {
      source  = "hashicorp/random"
      version = "3.7.2"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "3.6.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.38.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 3.1.0"
    }
  }
  # =============================
  # Backend Configuration
  # =============================
  #
  # LOCAL DEVELOPMENT:
  #   - Uncomment the 'local' backend block below to use local state.
  #   - Set 'tenant_id' and 'subscription_id' in your environments/*.tfvars file.
  #   - Comment out the 'azurerm' backend block.
  #
  # PIPELINE (AZURE DEVOPS):
  #   - Use the 'azurerm' backend block (uncomment below, comment out 'local').
  #   - 'tenant_id' and 'subscription_id' are appended to tfvars at runtime.
  #   - Backend config is provided via backend.tfvars generated by the pipeline.
  #
  # Uncomment ONE backend block as appropriate:
  #
  # backend "local" {
  #   path = "terraform.tfstate"
  # }
  #
  backend "azurerm" {
  # Configuration provided via backend.tfvars during terraform init
  # Values: subscription_id, resource_group_name, storage_account_name, container_name, key, use_azuread_auth
  }
}

provider "azurerm" {
  resource_provider_registrations = "extended"
  tenant_id                       = var.tenant_id # Set via tfvars (local) or pipeline (CI)
  subscription_id                 = var.subscription_id
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
}

provider "azurerm" {
  resource_provider_registrations = "none"
  alias                           = "management"
  subscription_id                 = "42dedbdb-3ad0-438c-a796-66bb1c08686a"
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
}

provider "azurerm" {
  resource_provider_registrations = "none"
  alias                           = "connectivity"
  subscription_id                 = "2bb0667b-d883-4406-b19a-a3083ba05bd8"
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
}
